version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./conf.d
        target: /etc/nginx/conf.d/
    ports:
      - "80:80"
    deploy:
      replicas: 1

  app1:
    image: app1:0.0.2
    expose:
      - 9090
    environment:
      - name=app1
    deploy:
      replicas: 5

  app2:
    image: app2:0.0.2
    expose:
      - 9090
    environment:
      - name=app2
    deploy:
      replicas: 5
